export type SportTakeMap = Record<string, string[]>;

function buildTakes(count: number, marquee: string[], subjects: string[], comparisons: string[], concepts: string[], policies: string[]): string[] {
  const takes = new Set<string>(marquee);
  const templates = [
    (a:string,b:string,c:string)=>`${a} should rank ahead of ${b} because of ${c}.`,
    (a:string,b:string,c:string)=>`${a} had a stronger case than ${b} when judging ${c}.`,
    (a:string,b:string,c:string)=>`${c} should matter more than trophies when comparing ${a} and ${b}.`,
    (a:string,b:string,c:string)=>`${a} is overrated when evaluated mainly through ${c}.`,
    (a:string,b:string,c:string)=>`${a} is underrated when evaluated through ${c}.`,
    (a:string,b:string,c:string)=>`A shorter elite peak from ${a} is more valuable than the longer career of ${b}.`,
    (a:string,b:string,c:string)=>`${a} would be more successful than ${b} in a different era because of ${c}.`,
    (a:string,b:string,c:string)=>`${a} had a greater influence on the sport than ${b}.`,
  ];
  let i = 0;
  while (takes.size < count) {
    const a = subjects[i % subjects.length];
    let b = comparisons[Math.floor(i / subjects.length) % comparisons.length];
    if (a === b) b = comparisons[(Math.floor(i / subjects.length) + 1) % comparisons.length];
    const c = concepts[Math.floor(i / (subjects.length * comparisons.length)) % concepts.length];
    const template = templates[Math.floor(i / (subjects.length * comparisons.length * concepts.length)) % templates.length];
    takes.add(template(a,b,c));
    if (takes.size < count) {
      const policy = policies[i % policies.length];
      const policyFrames = [
        `${policy} has improved the sport.`,
        `${policy} creates more problems than it solves.`,
        `The sport would be better without ${policy}.`,
        `${policy} should be expanded rather than restricted.`,
      ];
      takes.add(policyFrames[i % policyFrames.length]);
    }
    i++;
    if (i > count * 50) throw new Error("Unable to generate enough unique takes");
  }
  return Array.from(takes).slice(0,count);
}

export const TAKE_COUNTS: Record<string, number> = {
  "Soccer": 350,
  "Basketball": 250,
  "Football": 250,
  "Baseball": 200,
  "Hockey": 250,
  "UFC": 200,
  "Tennis": 100,
  "Formula 1": 100,
  "Golf": 100,
  "College Sports": 150,
};

export const TAKES: SportTakeMap = {
  "Soccer": buildTakes(350, ["Prime Neymar was better than prime Ronaldinho.", "Lionel Messi's 2012 was the greatest individual season in soccer history.", "A Champions League title matters more than a domestic league title.", "A player can be the greatest ever without winning a World Cup.", "Pep Guardiola is the greatest club manager ever.", "Cristiano Ronaldo is the greatest Champions League player ever.", "The Ballon d’Or places too much weight on team trophies.", "International soccer is harder to dominate than club soccer.", "A treble is more impressive than an unbeaten league season.", "Goalkeepers are undervalued in all-time rankings."], ["Lionel Messi", "Cristiano Ronaldo", "Pelé", "Diego Maradona", "Neymar", "Ronaldinho", "Kylian Mbappé", "Erling Haaland", "Zinedine Zidane", "Ronaldo Nazário", "Thierry Henry", "Andrés Iniesta", "Xavi", "Luka Modrić", "Kevin De Bruyne", "Mohamed Salah", "Luis Suárez", "Robert Lewandowski", "Karim Benzema", "Jude Bellingham", "Vinícius Júnior", "Bukayo Saka", "Harry Kane", "Sergio Ramos", "Virgil van Dijk", "Paolo Maldini", "Franz Beckenbauer", "Manuel Neuer", "Gianluigi Buffon", "Iker Casillas", "Pep Guardiola", "José Mourinho", "Carlo Ancelotti", "Sir Alex Ferguson", "Arsène Wenger", "Barcelona", "Real Madrid", "Manchester United", "Liverpool", "Arsenal", "Bayern Munich", "AC Milan", "Inter Milan", "Juventus", "Paris Saint-Germain", "Manchester City", "Argentina", "Brazil", "France", "Germany", "Spain", "England"], ["Lionel Messi", "Cristiano Ronaldo", "Pelé", "Diego Maradona", "Neymar", "Ronaldinho", "Kylian Mbappé", "Erling Haaland", "Zinedine Zidane", "Ronaldo Nazário", "Thierry Henry", "Andrés Iniesta", "Xavi", "Luka Modrić", "Kevin De Bruyne", "Mohamed Salah", "Robert Lewandowski", "Karim Benzema", "Sergio Ramos", "Virgil van Dijk", "Paolo Maldini", "Franz Beckenbauer", "Manuel Neuer", "Gianluigi Buffon", "Pep Guardiola", "José Mourinho", "Carlo Ancelotti", "Sir Alex Ferguson", "Barcelona", "Real Madrid", "Manchester United", "Liverpool", "Arsenal", "Bayern Munich", "AC Milan", "Manchester City", "Argentina", "Brazil", "France", "Spain"], ["peak ability", "career longevity", "big-game performance", "trophy record", "statistical production", "playmaking", "defensive impact", "leadership", "versatility", "international résumé", "club résumé", "technical skill", "tactical intelligence", "consistency", "influence on the sport"], ["VAR", "the away-goals rule", "financial fair play", "expanded international tournaments", "five substitutions", "salary caps", "promotion and relegation", "winter World Cups", "extra time before penalties", "the offside rule", "transfer spending limits", "domestic cup replays", "international breaks", "seeded Champions League draws", "the Club World Cup"]),
  "Basketball": buildTakes(250, ["LeBron James is the greatest basketball player ever.", "Peak Shaquille O’Neal was more dominant than peak Nikola Jokić.", "Defense is more important than shooting in the playoffs.", "Michael Jordan had the greatest peak in NBA history.", "Stephen Curry changed basketball more than any modern player.", "Championship rings are overrated in individual player debates.", "The three-point revolution has improved basketball.", "A dominant center is still the best foundation for a championship team."], ["Michael Jordan", "LeBron James", "Kareem Abdul-Jabbar", "Magic Johnson", "Larry Bird", "Kobe Bryant", "Shaquille O’Neal", "Tim Duncan", "Stephen Curry", "Kevin Durant", "Nikola Jokić", "Giannis Antetokounmpo", "Hakeem Olajuwon", "Wilt Chamberlain", "Bill Russell", "Oscar Robertson", "Jerry West", "Kevin Garnett", "Dirk Nowitzki", "Dwyane Wade", "Allen Iverson", "Steve Nash", "Chris Paul", "James Harden", "Kawhi Leonard", "Anthony Davis", "Jayson Tatum", "Luka Dončić", "Shai Gilgeous-Alexander", "Victor Wembanyama", "Boston Celtics", "Los Angeles Lakers", "Chicago Bulls", "Golden State Warriors", "San Antonio Spurs", "Miami Heat", "Denver Nuggets", "New York Knicks", "Philadelphia 76ers", "Detroit Pistons"], ["Michael Jordan", "LeBron James", "Kareem Abdul-Jabbar", "Magic Johnson", "Larry Bird", "Kobe Bryant", "Shaquille O’Neal", "Tim Duncan", "Stephen Curry", "Kevin Durant", "Nikola Jokić", "Giannis Antetokounmpo", "Hakeem Olajuwon", "Wilt Chamberlain", "Bill Russell", "Kevin Garnett", "Dirk Nowitzki", "Dwyane Wade", "Allen Iverson", "Chris Paul", "James Harden", "Kawhi Leonard", "Luka Dončić"], ["peak dominance", "career value", "playoff performance", "offensive impact", "defensive impact", "shot creation", "efficiency", "leadership", "versatility", "durability", "clutch play", "basketball IQ", "spacing impact", "team success", "individual awards"], ["the play-in tournament", "load management", "the three-point line", "defensive three seconds", "the salary cap", "the draft lottery", "conference seeding", "coach’s challenges", "the 65-game awards rule", "expansion", "shortened regular seasons", "in-season tournaments", "hand-checking rules", "maximum contracts", "one-and-done eligibility"]),
  "Football": buildTakes(250, ["Quarterback wins are an overrated statistic.", "The 2007 Patriots were better than the 1972 Dolphins.", "Running backs are still worth first-round draft picks.", "Tom Brady is the greatest football player ever.", "Peak Patrick Mahomes is the best quarterback ever.", "Defense still wins championships in the modern NFL.", "The NFL regular season should remain 17 games.", "A great offensive line is more valuable than an elite wide receiver."], ["Tom Brady", "Patrick Mahomes", "Peyton Manning", "Joe Montana", "Aaron Rodgers", "Dan Marino", "John Elway", "Drew Brees", "Brett Favre", "Johnny Unitas", "Jerry Rice", "Randy Moss", "Terrell Owens", "Calvin Johnson", "Larry Fitzgerald", "Rob Gronkowski", "Travis Kelce", "Barry Sanders", "Walter Payton", "Emmitt Smith", "Jim Brown", "Adrian Peterson", "LaDainian Tomlinson", "Lawrence Taylor", "Reggie White", "Ray Lewis", "Aaron Donald", "Deion Sanders", "Ed Reed", "J.J. Watt", "New England Patriots", "Kansas City Chiefs", "Pittsburgh Steelers", "Dallas Cowboys", "San Francisco 49ers", "Green Bay Packers", "New York Giants", "Philadelphia Eagles", "Baltimore Ravens", "Denver Broncos"], ["Tom Brady", "Patrick Mahomes", "Peyton Manning", "Joe Montana", "Aaron Rodgers", "Dan Marino", "Jerry Rice", "Randy Moss", "Terrell Owens", "Calvin Johnson", "Rob Gronkowski", "Travis Kelce", "Barry Sanders", "Walter Payton", "Emmitt Smith", "Jim Brown", "Lawrence Taylor", "Reggie White", "Ray Lewis", "Aaron Donald", "Deion Sanders", "Ed Reed"], ["peak performance", "career longevity", "playoff résumé", "regular-season production", "positional value", "leadership", "clutch play", "efficiency", "durability", "supporting cast", "era-adjusted dominance", "versatility", "individual awards", "team success", "impact on strategy"], ["the 17-game season", "overtime rules", "the franchise tag", "the salary cap", "the draft order", "roughing-the-passer rules", "instant replay", "Thursday Night Football", "international games", "the kickoff format", "two-point conversions", "playoff expansion", "guaranteed contracts", "rookie wage scales", "on-side kick rules"]),
  "Baseball": buildTakes(200, ["Barry Bonds was the greatest hitter in baseball history.", "Shohei Ohtani is the most talented baseball player ever.", "Batting average is an outdated way to judge hitters.", "Babe Ruth is still the greatest baseball player ever.", "Pitcher wins should not matter in award voting.", "The designated hitter improves baseball.", "A dominant five-year peak can outweigh career longevity.", "Defense is undervalued in Hall of Fame debates."], ["Babe Ruth", "Willie Mays", "Barry Bonds", "Hank Aaron", "Ted Williams", "Mickey Mantle", "Ty Cobb", "Lou Gehrig", "Stan Musial", "Ken Griffey Jr.", "Albert Pujols", "Mike Trout", "Shohei Ohtani", "Alex Rodriguez", "Derek Jeter", "Ichiro Suzuki", "Rickey Henderson", "Roberto Clemente", "Pedro Martínez", "Roger Clemens", "Randy Johnson", "Greg Maddux", "Sandy Koufax", "Nolan Ryan", "Clayton Kershaw", "Mariano Rivera", "New York Yankees", "Boston Red Sox", "Los Angeles Dodgers", "St. Louis Cardinals", "San Francisco Giants", "Chicago Cubs", "Atlanta Braves", "Houston Astros", "Philadelphia Phillies"], ["Babe Ruth", "Willie Mays", "Barry Bonds", "Hank Aaron", "Ted Williams", "Mickey Mantle", "Ty Cobb", "Ken Griffey Jr.", "Albert Pujols", "Mike Trout", "Shohei Ohtani", "Alex Rodriguez", "Derek Jeter", "Ichiro Suzuki", "Rickey Henderson", "Pedro Martínez", "Roger Clemens", "Randy Johnson", "Greg Maddux", "Sandy Koufax", "Nolan Ryan", "Clayton Kershaw", "Mariano Rivera"], ["peak hitting", "career value", "power", "on-base ability", "defense", "baserunning", "pitching dominance", "postseason performance", "durability", "era-adjusted production", "versatility", "consistency", "clutch reputation", "individual awards", "team success"], ["the pitch clock", "the designated hitter", "expanded playoffs", "the shift restrictions", "robot umpires", "seven-inning doubleheaders", "extra-inning runners", "salary caps", "revenue sharing", "Hall of Fame voting", "the luxury tax", "interleague play", "wild-card series", "service-time rules", "trade deadlines"]),
  "Hockey": buildTakes(250, ["Wayne Gretzky's records make him the clear greatest hockey player ever.", "Goalies are more important than centers in the playoffs.", "The salary cap has improved the NHL.", "Bobby Orr had the greatest peak in hockey history.", "Mario Lemieux was the most talented player ever.", "Playoff performance should matter more than regular-season awards.", "Connor McDavid is already an all-time top-five player.", "The Presidents’ Trophy is undervalued."], ["Wayne Gretzky", "Mario Lemieux", "Bobby Orr", "Gordie Howe", "Sidney Crosby", "Connor McDavid", "Alexander Ovechkin", "Jaromír Jágr", "Steve Yzerman", "Mark Messier", "Joe Sakic", "Peter Forsberg", "Pavel Datsyuk", "Nicklas Lidström", "Ray Bourque", "Patrick Roy", "Martin Brodeur", "Dominik Hašek", "Carey Price", "Auston Matthews", "Nathan MacKinnon", "Nikita Kucherov", "Leon Draisaitl", "Cale Makar", "David Pastrňák", "Boston Bruins", "Montreal Canadiens", "Toronto Maple Leafs", "Detroit Red Wings", "Edmonton Oilers", "Pittsburgh Penguins", "Colorado Avalanche", "New York Rangers", "Chicago Blackhawks", "Tampa Bay Lightning", "New Jersey Devils", "Philadelphia Flyers", "Vancouver Canucks", "Calgary Flames", "Ottawa Senators"], ["Wayne Gretzky", "Mario Lemieux", "Bobby Orr", "Gordie Howe", "Sidney Crosby", "Connor McDavid", "Alexander Ovechkin", "Jaromír Jágr", "Steve Yzerman", "Joe Sakic", "Peter Forsberg", "Pavel Datsyuk", "Nicklas Lidström", "Ray Bourque", "Patrick Roy", "Martin Brodeur", "Dominik Hašek", "Carey Price", "Auston Matthews", "Nathan MacKinnon", "Nikita Kucherov", "Cale Makar"], ["peak dominance", "career longevity", "playoff performance", "goal scoring", "playmaking", "two-way impact", "defensive value", "goaltending", "leadership", "durability", "era-adjusted production", "special-teams impact", "individual awards", "team success", "influence on the sport"], ["the salary cap", "three-on-three overtime", "the shootout", "the playoff format", "the draft lottery", "the points system", "fighting", "video review", "coach’s challenges", "expansion", "wild-card seeding", "the trapezoid rule", "international-sized ice", "LTIR rules", "the instigator rule"]),
  "UFC": buildTakes(200, ["Georges St-Pierre is the greatest mixed martial artist ever.", "Title defenses matter more than becoming a double champion.", "Wrestling is the most important base for MMA.", "Jon Jones has the strongest résumé in MMA history.", "Khabib Nurmagomedov had the most dominant prime ever.", "Finishing ability is overrated in GOAT debates.", "Moving up in weight matters more than defending one belt repeatedly.", "Judges should reward damage more than control."], ["Georges St-Pierre", "Jon Jones", "Anderson Silva", "Demetrious Johnson", "José Aldo", "Khabib Nurmagomedov", "Fedor Emelianenko", "Amanda Nunes", "Valentina Shevchenko", "Conor McGregor", "Islam Makhachev", "Alexander Volkanovski", "Max Holloway", "Charles Oliveira", "Dustin Poirier", "Justin Gaethje", "Israel Adesanya", "Alex Pereira", "Daniel Cormier", "Stipe Miocic", "Francis Ngannou", "Tom Aspinall", "Leon Edwards", "Kamaru Usman", "Joanna Jędrzejczyk", "Ronda Rousey", "Cris Cyborg", "B.J. Penn", "Matt Hughes", "Chuck Liddell"], ["Georges St-Pierre", "Jon Jones", "Anderson Silva", "Demetrious Johnson", "José Aldo", "Khabib Nurmagomedov", "Fedor Emelianenko", "Amanda Nunes", "Valentina Shevchenko", "Conor McGregor", "Islam Makhachev", "Alexander Volkanovski", "Max Holloway", "Charles Oliveira", "Israel Adesanya", "Alex Pereira", "Daniel Cormier", "Stipe Miocic", "Francis Ngannou", "Kamaru Usman"], ["peak dominance", "career longevity", "title defenses", "opponent quality", "finishing ability", "wrestling", "striking", "submission skill", "fight IQ", "versatility", "activity level", "multi-division success", "damage", "control time", "résumé depth"], ["open scoring", "five-round non-title main events", "the 10-point must system", "weight cutting", "interim titles", "immediate rematches", "judging criteria", "glove design", "hydration testing", "one-night tournaments", "champion clauses", "performance bonuses", "grounded-opponent rules", "12-to-6 elbows", "division expansion"]),
  "Tennis": buildTakes(100, ["Novak Djokovic is the greatest tennis player ever.", "Serena Williams is the greatest women’s tennis player ever.", "Grand Slam titles are the best measure of greatness.", "Clay-court dominance should count equally to all-surface versatility.", "The best-of-five format should remain in men’s Grand Slam tennis."], ["Novak Djokovic", "Roger Federer", "Rafael Nadal", "Pete Sampras", "Rod Laver", "Björn Borg", "Andre Agassi", "John McEnroe", "Jimmy Connors", "Andy Murray", "Carlos Alcaraz", "Jannik Sinner", "Serena Williams", "Steffi Graf", "Martina Navratilova", "Chris Evert", "Margaret Court", "Venus Williams", "Justine Henin", "Iga Świątek", "Aryna Sabalenka", "Naomi Osaka"], ["Novak Djokovic", "Roger Federer", "Rafael Nadal", "Pete Sampras", "Rod Laver", "Björn Borg", "Andre Agassi", "Andy Murray", "Carlos Alcaraz", "Jannik Sinner", "Serena Williams", "Steffi Graf", "Martina Navratilova", "Chris Evert", "Venus Williams", "Iga Świątek"], ["Grand Slam résumé", "peak level", "career longevity", "all-surface versatility", "serve quality", "return quality", "mental toughness", "rivalry strength", "dominance", "consistency", "Olympic résumé", "head-to-head record", "era strength", "movement", "shot-making"], ["best-of-five matches", "electronic line calling", "coaching during matches", "fifth-set tiebreaks", "equal prize money", "ranking-point rules", "protected rankings", "court-speed standardization", "night sessions", "the tennis calendar", "seedings", "medical timeouts", "let serves", "on-court microphones", "mixed-team events"]),
  "Formula 1": buildTakes(100, ["Lewis Hamilton is the greatest Formula 1 driver ever.", "Max Verstappen has the highest peak in Formula 1 history.", "A driver’s championship matters more than constructor dominance.", "Modern reliability makes cross-era comparisons unfair.", "Sprint races improve Formula 1 weekends."], ["Lewis Hamilton", "Michael Schumacher", "Ayrton Senna", "Juan Manuel Fangio", "Max Verstappen", "Alain Prost", "Sebastian Vettel", "Fernando Alonso", "Niki Lauda", "Jackie Stewart", "Jim Clark", "Nigel Mansell", "Kimi Räikkönen", "Mika Häkkinen", "Nelson Piquet", "Red Bull Racing", "Ferrari", "Mercedes", "McLaren", "Williams", "Lotus", "Renault"], ["Lewis Hamilton", "Michael Schumacher", "Ayrton Senna", "Juan Manuel Fangio", "Max Verstappen", "Alain Prost", "Sebastian Vettel", "Fernando Alonso", "Niki Lauda", "Jackie Stewart", "Jim Clark", "Kimi Räikkönen"], ["qualifying pace", "race pace", "wet-weather skill", "career longevity", "championship résumé", "team-building impact", "consistency", "wheel-to-wheel racing", "technical feedback", "adaptability", "peak dominance", "error avoidance", "car disadvantage performance", "strategy execution", "teammate performance"], ["sprint races", "budget caps", "DRS", "ground-effect regulations", "refueling", "team orders", "reverse-grid proposals", "the points system", "track limits", "safety-car restarts", "cost-cap penalties", "testing limits", "engine freezes", "street circuits", "super-license rules"]),
  "Golf": buildTakes(100, ["Tiger Woods had the greatest peak in golf history.", "Jack Nicklaus is the greatest golfer ever.", "Major championships matter too much in player rankings.", "The Ryder Cup is more entertaining than individual stroke-play events.", "Driving distance has become too important in professional golf."], ["Tiger Woods", "Jack Nicklaus", "Arnold Palmer", "Gary Player", "Ben Hogan", "Sam Snead", "Bobby Jones", "Phil Mickelson", "Rory McIlroy", "Brooks Koepka", "Jordan Spieth", "Scottie Scheffler", "Jon Rahm", "Dustin Johnson", "Seve Ballesteros", "Tom Watson", "Annika Sörenstam", "Mickey Wright", "Lorena Ochoa", "Nelly Korda"], ["Tiger Woods", "Jack Nicklaus", "Arnold Palmer", "Gary Player", "Ben Hogan", "Sam Snead", "Phil Mickelson", "Rory McIlroy", "Brooks Koepka", "Jordan Spieth", "Scottie Scheffler", "Jon Rahm", "Annika Sörenstam", "Lorena Ochoa"], ["major-championship résumé", "peak dominance", "career longevity", "ball striking", "putting", "driving", "short game", "mental toughness", "course management", "consistency", "international success", "match-play skill", "era strength", "clutch performance", "influence on the sport"], ["equipment rollbacks", "the cut line", "pace-of-play penalties", "match play", "major-championship exemptions", "world-ranking points", "shot clocks", "team golf", "course setup", "distance limits", "anchored putting", "green-reading books", "Ryder Cup captain’s picks", "playoff formats", "amateur-status rules"]),
  "College Sports": buildTakes(150, ["College athletes should be treated as employees.", "The College Football Playoff should have fewer automatic bids.", "Name, image, and likeness rules have improved college sports.", "Conference realignment has hurt traditional rivalries.", "The transfer portal gives athletes too much freedom.", "March Madness is the best postseason tournament in American sports."], ["Alabama football", "Georgia football", "Ohio State football", "Michigan football", "Notre Dame football", "USC football", "Texas football", "Oklahoma football", "Clemson football", "LSU football", "Penn State football", "Florida State football", "Duke basketball", "North Carolina basketball", "Kentucky basketball", "Kansas basketball", "UConn basketball", "UCLA basketball", "Gonzaga basketball", "Villanova basketball", "the SEC", "the Big Ten", "the Big 12", "the ACC", "the College Football Playoff", "March Madness", "the Heisman Trophy", "the transfer portal", "NIL collectives", "college baseball"], ["Alabama football", "Georgia football", "Ohio State football", "Michigan football", "Notre Dame football", "USC football", "Texas football", "Oklahoma football", "Clemson football", "LSU football", "Duke basketball", "North Carolina basketball", "Kentucky basketball", "Kansas basketball", "UConn basketball", "UCLA basketball", "the SEC", "the Big Ten", "the Big 12", "the ACC"], ["historic greatness", "recent dominance", "recruiting success", "player development", "coaching", "postseason performance", "conference strength", "rivalry importance", "tradition", "fan atmosphere", "academic standards", "NFL or NBA preparation", "consistency", "program influence", "championship résumé"], ["NIL rules", "the transfer portal", "conference realignment", "playoff expansion", "automatic bids", "athlete employment", "revenue sharing", "early signing periods", "redshirt rules", "conference championship games", "bowl-game opt-outs", "one-and-done basketball", "March Madness expansion", "home playoff games", "recruiting calendars"]),
};

export const TOTAL_TAKES = Object.values(TAKE_COUNTS).reduce((sum,count)=>sum+count,0);
